// Search
export const SEARCH_TOGGLE = 'SEARCH_TOGGLE'

// On Mobile view Rightside toggle
export const MOBILE_RIGHT_TOGGLE = 'MOBILE_RIGHT_TOGGLE'


// Rightsidebar on click of message icon in header
export const RIGHT_SIDEBAR = 'RIGHT_SIDEBAR'

// SwitchToggle
export const SWITCH_TOGGLE = 'SWITCH_TOGGLE'


//CUSTOMIZER 
export const ADD_COSTOMIZER ="ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS = "ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIX_BACKGROUND_LAYOUT = "ADD_MIX_BACKGROUND_LAYOUT";
export const ADD_SIDEBAR_BACKGROUND = "ADD_SIDEBAR_BACKGROUND";
export const ROUTER_ANIMATION = "ROUTER_ANIMATION";


export const type = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    SUCCESSFUL_LOG: 'SUCCESSFUL_LOG',
    SUCCESSFUL_REG: 'SUCCESSFUL_REG',
    GET_SINGLE_BUSINESS: 'GET_SINGLE_BUSINESS',
    ERROR_GETTING_USER_BUSINESS: 'ERROR_GETTING_USER_BUSINESS',
    USER_HAVE_NO_BUSINESS: 'USER_HAVE_NO_BUSINESS',
    CREATE_BUSINESS: 'CREATE_BUSINESS',
    REQUESTING_CREATE_BUSINESS: 'REQUESTING_CREATE_BUSINESS'
}
